/** Marker comment embedded in forgectl-generated PR descriptions. */
const FORGECTL_MARKER = "<!-- forgectl-generated -->";

/** Data needed to build a PR description. */
export interface PRDescriptionData {
  issueNumber: number;
  changes: string[];
  validationResults: { step: string; passed: boolean }[];
  cost: {
    estimated_usd: string;
    input_tokens: number;
    output_tokens: number;
  };
  workflow: string;
  agent: string;
  /** Optional rich context fields for enhanced PR descriptions. */
  issueIdentifier?: string;
  issueTitle?: string;
  repoSlug?: string;
  issueDescription?: string;
  diffStat?: string;
}

/** Octokit-like interface for PR API calls. */
interface OctokitPulls {
  rest: {
    pulls: {
      list(params: {
        owner: string;
        repo: string;
        head: string;
        state: string;
      }): Promise<{ data: Array<{ number: number; body: string | null }> }>;
      create(params: {
        owner: string;
        repo: string;
        title: string;
        body: string;
        head: string;
        base: string;
      }): Promise<{ data: { number: number; html_url: string } }>;
      update(params: {
        owner: string;
        repo: string;
        pull_number: number;
        body: string;
      }): Promise<unknown>;
    };
  };
}

/**
 * Extract acceptance criteria from an issue description.
 * Looks for sections headed by "Acceptance criteria:", "Requirements:",
 * or "Acceptance Criteria:" (case-insensitive) and returns the content
 * until the next markdown heading or end of text.
 */
export function extractAcceptanceCriteria(description: string): string | null {
  const match = description.match(
    /(?:^|\n)#+\s*(?:acceptance\s+criteria|requirements)\s*:?\s*\n([\s\S]*?)(?=\n#|\n---|\n\*\*[A-Z]|$)/i,
  );
  if (match) return match[1].trim() || null;

  // Also try bold-label style: **Acceptance criteria:**
  const boldMatch = description.match(
    /\*\*(?:acceptance\s+criteria|requirements)\s*:?\s*\*\*\s*:?\s*\n([\s\S]*?)(?=\n#|\n---|\n\*\*[A-Z]|$)/i,
  );
  if (boldMatch) return boldMatch[1].trim() || null;

  return null;
}

/**
 * Build a PR description from run data.
 * Includes linked issue, changes, validation, cost, and forgectl footer.
 * Embeds a forgectl-generated marker for safe overwrite detection.
 * When rich context fields are provided, includes full ticket context,
 * requirements, diff stat summary, and acceptance criteria.
 */
export function buildPRDescription(data: PRDescriptionData): string {
  const lines: string[] = [];

  // Marker for detecting forgectl-generated descriptions
  lines.push(FORGECTL_MARKER);
  lines.push("");

  // Linked issue
  lines.push(`Closes #${data.issueNumber}`);
  lines.push("");

  // Rich context section (when ticket context is available)
  if (data.issueIdentifier || data.repoSlug) {
    lines.push("## Context");
    if (data.issueIdentifier && data.issueTitle) {
      lines.push(`**Linear:** ${data.issueIdentifier} — ${data.issueTitle}`);
    } else if (data.issueIdentifier) {
      lines.push(`**Ticket:** ${data.issueIdentifier}`);
    }
    if (data.repoSlug) {
      lines.push(`**Repo:** ${data.repoSlug}`);
    }
    lines.push("");
  }

  // Requirements section (full ticket description)
  if (data.issueDescription) {
    lines.push("## Requirements (from ticket)");
    lines.push("");
    lines.push(data.issueDescription);
    lines.push("");
  }

  // Changes section
  lines.push("## Changes");
  lines.push("");
  if (data.diffStat) {
    lines.push("```");
    lines.push(data.diffStat);
    lines.push("```");
    lines.push("");
  }
  for (const change of data.changes) {
    lines.push(`- \`${change}\``);
  }
  lines.push("");

  // Acceptance criteria (extracted from ticket description)
  if (data.issueDescription) {
    const ac = extractAcceptanceCriteria(data.issueDescription);
    if (ac) {
      lines.push("## Acceptance Criteria");
      lines.push("");
      lines.push(ac);
      lines.push("");
    }
  }

  // Validation section
  lines.push("## Validation");
  lines.push("");
  for (const v of data.validationResults) {
    const icon = v.passed ? "pass" : "FAIL";
    lines.push(`- [${icon}] **${v.step}**`);
  }
  lines.push("");

  // Cost section
  lines.push("## Cost");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Input tokens | ${data.cost.input_tokens} |`);
  lines.push(`| Output tokens | ${data.cost.output_tokens} |`);
  lines.push(`| Estimated cost | ${data.cost.estimated_usd} |`);
  lines.push("");

  // Separator and footer
  lines.push("---");
  lines.push("");
  lines.push(`_Agent: ${data.agent} | Workflow: ${data.workflow}_`);
  lines.push("");
  lines.push("_Generated by [forgectl](https://github.com/forgectl/forgectl)_");

  return lines.join("\n");
}

/** Input for building a rich PR body from issue context. */
export interface RichPRBodyInput {
  issueId: string;
  issueIdentifier: string;
  issueTitle: string;
  issueDescription?: string;
  repoSlug?: string;
  diffStat?: string;
  validationResults?: { step: string; passed: boolean }[];
}

/**
 * Build a rich PR body from issue context.
 * Used by the dispatcher when creating PRs via tracker or GitHub App APIs.
 */
export function buildRichPRBody(input: RichPRBodyInput): string {
  const lines: string[] = [];

  lines.push(`Closes #${input.issueId}`);
  lines.push("");

  // Context
  lines.push("## Context");
  lines.push(`**Linear:** ${input.issueIdentifier} — ${input.issueTitle}`);
  if (input.repoSlug) {
    lines.push(`**Repo:** ${input.repoSlug}`);
  }
  lines.push("");

  // Requirements
  if (input.issueDescription) {
    lines.push("## Requirements (from ticket)");
    lines.push("");
    lines.push(input.issueDescription);
    lines.push("");

    const ac = extractAcceptanceCriteria(input.issueDescription);
    if (ac) {
      lines.push("## Acceptance Criteria");
      lines.push("");
      lines.push(ac);
      lines.push("");
    }
  }

  // Changes
  if (input.diffStat) {
    lines.push("## Changes");
    lines.push("");
    lines.push("```");
    lines.push(input.diffStat);
    lines.push("```");
    lines.push("");
  }

  // Validation
  if (input.validationResults && input.validationResults.length > 0) {
    lines.push("## Validation");
    lines.push("");
    for (const v of input.validationResults) {
      const mark = v.passed ? "x" : " ";
      lines.push(`- [${mark}] ${v.step} passed`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("_Generated by [forgectl](https://github.com/forgectl/forgectl)_");

  return lines.join("\n");
}

/**
 * Update a PR's description with auto-generated content (by PR number).
 */
export async function updatePRDescription(
  octokit: OctokitPulls,
  owner: string,
  repo: string,
  prNumber: number,
  data: PRDescriptionData,
): Promise<void> {
  const body = buildPRDescription(data);
  await octokit.rest.pulls.update({
    owner,
    repo,
    pull_number: prNumber,
    body,
  });
}

/**
 * Create a PR for a branch if one doesn't already exist.
 * Returns the PR number if created, or undefined if a PR already exists.
 */
export async function createPRForBranch(
  octokit: OctokitPulls,
  owner: string,
  repo: string,
  branch: string,
  title: string,
  data: PRDescriptionData,
  base = "main",
): Promise<number | undefined> {
  // Check if PR already exists
  const existing = await octokit.rest.pulls.list({
    owner,
    repo,
    head: `${owner}:${branch}`,
    state: "open",
  });

  if (existing.data.length > 0) {
    return existing.data[0].number;
  }

  const body = buildPRDescription(data);
  const result = await octokit.rest.pulls.create({
    owner,
    repo,
    title,
    body,
    head: branch,
    base,
  });

  return result.data.number;
}

/**
 * Find a PR matching the given branch and update its description.
 * Skips update if:
 * - No open PR exists for the branch
 * - The existing PR body was written by a human (no forgectl-generated marker and non-null body)
 *
 * Safe to call as best-effort; caller should wrap in try/catch.
 */
export async function updatePRDescriptionForBranch(
  octokit: OctokitPulls,
  owner: string,
  repo: string,
  branch: string,
  data: PRDescriptionData,
): Promise<void> {
  const response = await octokit.rest.pulls.list({
    owner,
    repo,
    head: `${owner}:${branch}`,
    state: "open",
  });

  if (response.data.length === 0) {
    return; // No PR for this branch
  }

  const pr = response.data[0];

  // Preserve human-written descriptions: skip if body exists and has no forgectl marker
  if (pr.body !== null && pr.body !== "" && !pr.body.includes(FORGECTL_MARKER)) {
    return;
  }

  const body = buildPRDescription(data);
  await octokit.rest.pulls.update({
    owner,
    repo,
    pull_number: pr.number,
    body,
  });
}
