/** Data needed to build a PR description. */
export interface PRDescriptionData {
  issueNumber: number;
  changes: string[];
  validationResults: { step: string; passed: boolean }[];
  cost: {
    estimated_usd: string;
    input_tokens: number;
    output_tokens: number;
  };
  workflow: string;
  agent: string;
}

/** Octokit-like interface for PR update API calls. */
interface OctokitPulls {
  rest: {
    pulls: {
      update(params: {
        owner: string;
        repo: string;
        pull_number: number;
        body: string;
      }): Promise<unknown>;
    };
  };
}

/**
 * Build a PR description from run data.
 * Includes linked issue, changes, validation, cost, and forgectl footer.
 */
export function buildPRDescription(data: PRDescriptionData): string {
  const lines: string[] = [];

  // Linked issue
  lines.push(`Closes #${data.issueNumber}`);
  lines.push("");

  // Changes section
  lines.push("## Changes");
  lines.push("");
  for (const change of data.changes) {
    lines.push(`- \`${change}\``);
  }
  lines.push("");

  // Validation section
  lines.push("## Validation");
  lines.push("");
  for (const v of data.validationResults) {
    const icon = v.passed ? "pass" : "FAIL";
    lines.push(`- [${icon}] **${v.step}**`);
  }
  lines.push("");

  // Cost section
  lines.push("## Cost");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Input tokens | ${data.cost.input_tokens} |`);
  lines.push(`| Output tokens | ${data.cost.output_tokens} |`);
  lines.push(`| Estimated cost | ${data.cost.estimated_usd} |`);
  lines.push("");

  // Separator and footer
  lines.push("---");
  lines.push("");
  lines.push(`_Agent: ${data.agent} | Workflow: ${data.workflow}_`);
  lines.push("");
  lines.push("_Generated by [forgectl](https://github.com/forgectl/forgectl)_");

  return lines.join("\n");
}

/**
 * Update a PR's description with auto-generated content.
 */
export async function updatePRDescription(
  octokit: OctokitPulls,
  owner: string,
  repo: string,
  prNumber: number,
  data: PRDescriptionData,
): Promise<void> {
  const body = buildPRDescription(data);
  await octokit.rest.pulls.update({
    owner,
    repo,
    pull_number: prNumber,
    body,
  });
}
