/** Marker comment embedded in forgectl-generated PR descriptions. */
const FORGECTL_MARKER = "<!-- forgectl-generated -->";

/** Data needed to build a PR description. */
export interface PRDescriptionData {
  issueNumber: number;
  changes: string[];
  validationResults: { step: string; passed: boolean }[];
  cost: {
    estimated_usd: string;
    input_tokens: number;
    output_tokens: number;
  };
  workflow: string;
  agent: string;
}

/** Octokit-like interface for PR update and list API calls. */
interface OctokitPulls {
  rest: {
    pulls: {
      list(params: {
        owner: string;
        repo: string;
        head: string;
        state: string;
      }): Promise<{ data: Array<{ number: number; body: string | null }> }>;
      update(params: {
        owner: string;
        repo: string;
        pull_number: number;
        body: string;
      }): Promise<unknown>;
    };
  };
}

/**
 * Build a PR description from run data.
 * Includes linked issue, changes, validation, cost, and forgectl footer.
 * Embeds a forgectl-generated marker for safe overwrite detection.
 */
export function buildPRDescription(data: PRDescriptionData): string {
  const lines: string[] = [];

  // Marker for detecting forgectl-generated descriptions
  lines.push(FORGECTL_MARKER);
  lines.push("");

  // Linked issue
  lines.push(`Closes #${data.issueNumber}`);
  lines.push("");

  // Changes section
  lines.push("## Changes");
  lines.push("");
  for (const change of data.changes) {
    lines.push(`- \`${change}\``);
  }
  lines.push("");

  // Validation section
  lines.push("## Validation");
  lines.push("");
  for (const v of data.validationResults) {
    const icon = v.passed ? "pass" : "FAIL";
    lines.push(`- [${icon}] **${v.step}**`);
  }
  lines.push("");

  // Cost section
  lines.push("## Cost");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Input tokens | ${data.cost.input_tokens} |`);
  lines.push(`| Output tokens | ${data.cost.output_tokens} |`);
  lines.push(`| Estimated cost | ${data.cost.estimated_usd} |`);
  lines.push("");

  // Separator and footer
  lines.push("---");
  lines.push("");
  lines.push(`_Agent: ${data.agent} | Workflow: ${data.workflow}_`);
  lines.push("");
  lines.push("_Generated by [forgectl](https://github.com/forgectl/forgectl)_");

  return lines.join("\n");
}

/**
 * Update a PR's description with auto-generated content (by PR number).
 */
export async function updatePRDescription(
  octokit: OctokitPulls,
  owner: string,
  repo: string,
  prNumber: number,
  data: PRDescriptionData,
): Promise<void> {
  const body = buildPRDescription(data);
  await octokit.rest.pulls.update({
    owner,
    repo,
    pull_number: prNumber,
    body,
  });
}

/**
 * Find a PR matching the given branch and update its description.
 * Skips update if:
 * - No open PR exists for the branch
 * - The existing PR body was written by a human (no forgectl-generated marker and non-null body)
 *
 * Safe to call as best-effort; caller should wrap in try/catch.
 */
export async function updatePRDescriptionForBranch(
  octokit: OctokitPulls,
  owner: string,
  repo: string,
  branch: string,
  data: PRDescriptionData,
): Promise<void> {
  const response = await octokit.rest.pulls.list({
    owner,
    repo,
    head: `${owner}:${branch}`,
    state: "open",
  });

  if (response.data.length === 0) {
    return; // No PR for this branch
  }

  const pr = response.data[0];

  // Preserve human-written descriptions: skip if body exists and has no forgectl marker
  if (pr.body !== null && pr.body !== "" && !pr.body.includes(FORGECTL_MARKER)) {
    return;
  }

  const body = buildPRDescription(data);
  await octokit.rest.pulls.update({
    owner,
    repo,
    pull_number: pr.number,
    body,
  });
}
