/**
 * Sub-issue rollup module.
 *
 * Provides pure functions for building progress comments, searching for
 * marker-based rollup comments on GitHub issues, upsert logic, and a
 * terminal-state check. All functions accept a minimal RollupOctokitLike
 * interface so they are easily testable with mocks.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Minimal Octokit interface required by the rollup module. */
export interface RollupOctokitLike {
  rest: {
    issues: {
      listComments(params: {
        owner: string;
        repo: string;
        issue_number: number;
        per_page: number;
        page: number;
      }): Promise<{ data: Array<{ id: number; body?: string | null }> }>;
      createComment(params: {
        owner: string;
        repo: string;
        issue_number: number;
        body: string;
      }): Promise<{ data: { id: number } }>;
      updateComment(params: {
        owner: string;
        repo: string;
        comment_id: number;
        body: string;
      }): Promise<unknown>;
    };
  };
}

/** Status of a single child issue for progress rendering. */
export interface ChildStatus {
  /** Issue identifier (e.g. "42" or full node id). */
  id: string;
  /** Human-readable issue title. */
  title: string;
  /** URL to the issue on GitHub. */
  url: string;
  /** Current lifecycle state of the child. */
  state: "completed" | "in_progress" | "pending" | "failed" | "blocked";
  /** Optional short error summary shown for failed children. */
  errorSummary?: string;
}

// ---------------------------------------------------------------------------
// Marker helpers
// ---------------------------------------------------------------------------

const PER_PAGE = 100;

/**
 * Returns the hidden HTML comment marker used to identify the rollup comment.
 * Example: `<!-- forgectl:progress:parent-42 -->`
 */
export function buildRollupMarker(parentIssueNumber: number): string {
  return `<!-- forgectl:progress:parent-${parentIssueNumber} -->`;
}

// ---------------------------------------------------------------------------
// Comment search
// ---------------------------------------------------------------------------

/**
 * Paginate through all comments on `parentIssueNumber` and return the id of
 * the comment that contains the rollup marker, or null if not found.
 */
export async function findRollupCommentId(
  octokit: RollupOctokitLike,
  owner: string,
  repo: string,
  parentIssueNumber: number,
): Promise<number | null> {
  const marker = buildRollupMarker(parentIssueNumber);
  let page = 1;

  while (true) {
    const { data } = await octokit.rest.issues.listComments({
      owner,
      repo,
      issue_number: parentIssueNumber,
      per_page: PER_PAGE,
      page,
    });

    for (const comment of data) {
      if (comment.body && comment.body.includes(marker)) {
        return comment.id;
      }
    }

    // Stop when we get fewer results than a full page — no more pages.
    if (data.length < PER_PAGE) {
      return null;
    }

    page++;
  }
}

// ---------------------------------------------------------------------------
// Upsert
// ---------------------------------------------------------------------------

/**
 * Create or update the rollup comment on the parent issue.
 *
 * Self-healing: if the marker comment was deleted by a user, the next call
 * creates a fresh one rather than failing.
 */
export async function upsertRollupComment(
  octokit: RollupOctokitLike,
  owner: string,
  repo: string,
  parentIssueNumber: number,
  body: string,
): Promise<void> {
  const existingId = await findRollupCommentId(
    octokit,
    owner,
    repo,
    parentIssueNumber,
  );

  if (existingId !== null) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existingId,
      body,
    });
  } else {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: parentIssueNumber,
      body,
    });
  }
}

// ---------------------------------------------------------------------------
// Progress comment builder
// ---------------------------------------------------------------------------

const EMOJI: Record<ChildStatus["state"], string> = {
  completed: "✅",
  in_progress: "⏳",
  pending: "⬜",
  failed: "❌",
  blocked: "⛔",
};

/**
 * Build the full markdown body of the rollup progress comment.
 *
 * Format:
 * ```
 * <!-- forgectl:progress:parent-{N} -->
 * ## Sub-Issue Progress
 *
 * - [x] ✅ [Title](url)
 * - [ ] ⏳ [Title](url)
 * - [ ] ❌ [Title](url) — Failed: error summary
 *
 * **Progress: N/M complete**
 *
 * ---
 * _Generated by [forgectl](https://github.com/forgectl/forgectl)_
 * ```
 */
export function buildSubIssueProgressComment(
  parentIssueNumber: number,
  children: ChildStatus[],
): string {
  const marker = buildRollupMarker(parentIssueNumber);
  const lines: string[] = [];

  lines.push(marker);
  lines.push("## Sub-Issue Progress");
  lines.push("");

  for (const child of children) {
    const emoji = EMOJI[child.state];
    const checked = child.state === "completed" ? "x" : " ";
    let line = `- [${checked}] ${emoji} [${child.title}](${child.url})`;

    if (child.state === "failed" && child.errorSummary) {
      line += ` \u2014 Failed: ${child.errorSummary}`;
    }

    lines.push(line);
  }

  lines.push("");

  const completed = children.filter((c) => c.state === "completed").length;
  const total = children.length;
  lines.push(`**Progress: ${completed}/${total} complete**`);
  lines.push("");
  lines.push("---");
  lines.push(
    "_Generated by [forgectl](https://github.com/forgectl/forgectl)_",
  );

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Terminal state check
// ---------------------------------------------------------------------------

/**
 * Returns true only when every child in `childStates` is in `terminalStates`.
 * Returns false for an empty map (no children means nothing is done yet).
 */
export function allChildrenTerminal(
  childStates: Map<string, string>,
  terminalStates: Set<string>,
): boolean {
  if (childStates.size === 0) {
    return false;
  }
  for (const state of childStates.values()) {
    if (!terminalStates.has(state)) {
      return false;
    }
  }
  return true;
}
