import { describe, it, expect, vi } from "vitest";
import {
  buildPRDescription,
  updatePRDescription,
  type PRDescriptionData,
} from "../../src/github/pr-description.js";

function sampleData(): PRDescriptionData {
  return {
    issueNumber: 42,
    changes: ["src/foo.ts", "src/bar.ts"],
    validationResults: [
      { step: "typecheck", passed: true },
      { step: "test", passed: false },
    ],
    cost: {
      estimated_usd: "$0.05",
      input_tokens: 10000,
      output_tokens: 5000,
    },
    workflow: "code",
    agent: "claude",
  };
}

describe("buildPRDescription", () => {
  it("includes Closes #N linked issue reference", () => {
    const body = buildPRDescription(sampleData());
    expect(body).toContain("Closes #42");
  });

  it("includes changes list", () => {
    const body = buildPRDescription(sampleData());
    expect(body).toContain("## Changes");
    expect(body).toContain("src/foo.ts");
    expect(body).toContain("src/bar.ts");
  });

  it("includes validation results with pass/fail indicators", () => {
    const body = buildPRDescription(sampleData());
    expect(body).toContain("## Validation");
    expect(body).toContain("typecheck");
    expect(body).toContain("test");
  });

  it("includes cost breakdown", () => {
    const body = buildPRDescription(sampleData());
    expect(body).toContain("## Cost");
    expect(body).toContain("$0.05");
    expect(body).toContain("10000");
    expect(body).toContain("5000");
  });

  it("includes agent and workflow info", () => {
    const body = buildPRDescription(sampleData());
    expect(body).toContain("Agent: claude");
    expect(body).toContain("Workflow: code");
  });

  it("includes Generated by forgectl footer", () => {
    const body = buildPRDescription(sampleData());
    expect(body).toContain("Generated by [forgectl]");
  });
});

describe("updatePRDescription", () => {
  it("calls octokit.rest.pulls.update with generated body", async () => {
    const octokit = {
      rest: {
        pulls: {
          update: vi.fn().mockResolvedValue({}),
        },
      },
    };
    await updatePRDescription(octokit as any, "owner", "repo", 99, sampleData());
    expect(octokit.rest.pulls.update).toHaveBeenCalledWith({
      owner: "owner",
      repo: "repo",
      pull_number: 99,
      body: buildPRDescription(sampleData()),
    });
  });
});
